In [1]:
from PIL import Image
import numpy as np

image = Image.open('pexels-michael-block-1691617-3225517.jpg')

image_array = np.array(image)

print(image_array)


[[[220 230 240]
  [221 231 241]
  [219 232 241]
  ...
  [128 184 221]
  [129 185 222]
  [132 188 225]]

 [[220 230 240]
  [221 231 241]
  [221 231 241]
  ...
  [129 185 222]
  [129 185 222]
  [130 186 223]]

 [[220 230 240]
  [221 231 241]
  [221 231 241]
  ...
  [128 186 223]
  [127 185 222]
  [125 183 220]]

 ...

 [[ 74  67  57]
  [ 25  18   8]
  [ 24  17   9]
  ...
  [ 86  76  75]
  [ 94  84  83]
  [118 108 107]]

 [[ 74  67  57]
  [ 26  19   9]
  [ 26  19  11]
  ...
  [ 86  76  75]
  [ 94  84  83]
  [118 108 107]]

 [[ 74  67  57]
  [ 26  19   9]
  [ 27  20  12]
  ...
  [ 86  76  75]
  [ 93  83  82]
  [117 107 106]]]


In [3]:
print(image_array.shape)

(5830, 4664, 3)
