In [6]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

# Function to generate Gaussian noise matrix for each channel
def generate_gaussian_noise(shape, mean=0, std=5, seed=None):
    if seed is not None:
        np.random.seed(seed)
    noise = np.random.normal(mean, std, size=shape)  # Gaussian noise
    return noise

# Function to perform encryption step
def encrypt_image(image, steps=500, seed=123):
    encrypted_images = []
    noise_steps = []
    encrypted_image = image.copy()

    for step in range(steps):
        noise = generate_gaussian_noise(image.shape, mean=0, std=5, seed=seed + step)  # Generate Gaussian noise
        noise_steps.append(noise)
        encrypted_image = encrypted_image + noise  # Add noise
        encrypted_image = np.clip(encrypted_image, 0, 255)  # Clip to valid pixel range
        encrypted_images.append(encrypted_image)
        
        if step % 100 == 0:  # Print every 100 steps
            print(f"Encryption Step {step + 1}:")
            print(encrypted_image.astype(int))
    
    return encrypted_image, noise_steps

# Function to perform decryption step
def decrypt_image(encrypted_image, noise_steps):
    decrypted_image = encrypted_image.copy()

    for step, noise in enumerate(reversed(noise_steps)):
        decrypted_image = decrypted_image - noise  # Subtract the noise
        decrypted_image = np.clip(decrypted_image, 0, 255)  # Clip to valid pixel range
        
        if step % 100 == 0:  # Print every 100 steps
            print(f"Decryption Step {len(noise_steps) - step}:")
            print(decrypted_image.astype(int))

    return decrypted_image

# Function to display original, encrypted, and decrypted images
def show_images(original, encrypted, decrypted):
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    # Original Image
    axes[0].imshow(original.astype(np.uint8))
    axes[0].set_title("Original Image")
    axes[0].axis("off")
    
    # Encrypted Image
    axes[1].imshow(encrypted.astype(np.uint8))
    axes[1].set_title("Encrypted Image")
    axes[1].axis("off")
    
    # Decrypted Image
    axes[2].imshow(decrypted.astype(np.uint8))
    axes[2].set_title("Decrypted Image")
    axes[2].axis("off")
    
    plt.show()

# Main function
def main():
    # Load image from the specified path
    image_path = r"C:\Users\varun\OneDrive\Desktop\Desktop\DBIE\pexels-michael-block-1691617-3225517.jpg"
    original_image = Image.open(image_path).convert('RGB')  # Ensure it's in RGB format
    original_image = np.array(original_image)  # Convert to numpy array
    
    print("Original Image:")
    print(original_image)

    # Encrypt the image with Gaussian noise
    encrypted_image, noise_steps = encrypt_image(original_image, steps=500, seed=123)
    
    # Decrypt the image by reversing the noise steps
    decrypted_image = decrypt_image(encrypted_image, noise_steps)
    
    # Show the original, encrypted, and decrypted images
    show_images(original_image, encrypted_image, decrypted_image)

# Run the main function
main()


Original Image:
[[[220 230 240]
  [221 231 241]
  [219 232 241]
  ...
  [128 184 221]
  [129 185 222]
  [132 188 225]]

 [[220 230 240]
  [221 231 241]
  [221 231 241]
  ...
  [129 185 222]
  [129 185 222]
  [130 186 223]]

 [[220 230 240]
  [221 231 241]
  [221 231 241]
  ...
  [128 186 223]
  [127 185 222]
  [125 183 220]]

 ...

 [[ 74  67  57]
  [ 25  18   8]
  [ 24  17   9]
  ...
  [ 86  76  75]
  [ 94  84  83]
  [118 108 107]]

 [[ 74  67  57]
  [ 26  19   9]
  [ 26  19  11]
  ...
  [ 86  76  75]
  [ 94  84  83]
  [118 108 107]]

 [[ 74  67  57]
  [ 26  19   9]
  [ 27  20  12]
  ...
  [ 86  76  75]
  [ 93  83  82]
  [117 107 106]]]
Encryption Step 1:
[[[214 234 241]
  [213 228 249]
  [206 229 247]
  ...
  [134 186 215]
  [130 178 214]
  [135 188 223]]

 [[221 230 241]
  [220 236 244]
  [219 230 241]
  ...
  [128 169 224]
  [134 175 221]
  [126 184 227]]

 [[226 232 250]
  [224 231 242]
  [223 228 239]
  ...
  [131 192 221]
  [129 196 219]
  [129 197 223]]

 ...

 [[ 76  63  55]
 

MemoryError: Unable to allocate 622. MiB for an array with shape (5830, 4664, 3) and data type float64