In [2]:
import torch
# construct DDPM noise schedule
beta1 = 0.01
beta2 = 0.2
timesteps = 10
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
b_t = (beta2 - beta1) * torch.linspace(0, 1, timesteps + 1, device=device) + beta1 #b_t is a sequence of numbers (like a list) that tells us how much noise to add at each step.
a_t = 1 - b_t #This means a_t tells us how much of the original image is left after adding some noise.
ab_t = torch.cumsum(a_t.log(), dim=0).exp()  # sequence that accumulates the effects of adding noise over many steps.  
ab_t[0] = 1 #100% of the original image with no noise added yet.

In [3]:
print(b_t)
print(a_t)
print(ab_t)

tensor([0.0100, 0.0290, 0.0480, 0.0670, 0.0860, 0.1050, 0.1240, 0.1430, 0.1620,
        0.1810, 0.2000], device='cuda:0')
tensor([0.9900, 0.9710, 0.9520, 0.9330, 0.9140, 0.8950, 0.8760, 0.8570, 0.8380,
        0.8190, 0.8000], device='cuda:0')
tensor([1.0000, 0.9613, 0.9151, 0.8538, 0.7804, 0.6985, 0.6119, 0.5244, 0.4394,
        0.3599, 0.2879], device='cuda:0')
